### ISSUE TITLE
Nike URL Change?

### ISSUE THREAD

**Issue by PUNTxR** [sonya75/NikeAccountGenerator#1]
Did something change w the nike url? I've used this before and it worked but now I'm getting the following:

401 Client Error: Unauthorized for url: https://unite.nike.com/loginWithSetCookie?appVersion=302&experienceVersion=267&uxid=com.nike.commerce.nikedotcom.web&locale=zh_CN&backendEnvironment=identity&browser=Google%20Inc.&os=undefined&mobile=false&native=false

This is what displays on the browser:
{"error_description":"Unsupported Grant Type","error":"unsupported_grant_type"}

**Comment by beesley1994** [comment]
has this been fixed? im getting the same issue

**Comment by kfinest** [comment]
same

**Comment by Stiunit** [comment]
same

**Comment by julysses** [comment]
im getting: 
Bad Request for url: https://unite.nike.com/join?appVersion=369&experienceVersion=312&uxid=com.nike.commerce.nikedotcom.web&locale=zh_CN&backendEnvironment=identity&browser=Google%20Inc.&os=undefined&mobile=false&native=false

**Comment by sonya75** [comment]
I just looked into this few days ago and fixed it. Not sure when I will make it public though.

**Comment by dukai1011** [comment]
same here
