### ISSUE TITLE
I’m Getting Message | Issue, Try again later

### ISSUE THREAD

**Issue by sundog303** [sonya75/NikeAccountGenerator#10]
Getting the problem of - Message | Issue, Try later
Everything seems to be working good. Someone said Getsms is down. I was going to make some accounts before the OW drop tommorow. Anyone able to help or fill me in? Thank you.

**Comment by sundog303** [comment]
Update now I’m getting Manage | balance is not enough 
Yet the accounts I made did not get saved to nikeemails.txt

**Comment by sonya75** [comment]
Its not really a script issue. Getsms is having number shortage. Anyway, the script isn't working right now.
