### ISSUE TITLE
Error at nikegen.py run

### ISSUE THREAD

**Issue by Lifinest7** [sonya75/NikeAccountGenerator#13]
Here is the error i am receiving...

Henrys-MBP:NikeAccountGenerator-master HB77$ Python2 nikegen.py
Traceback (most recent call last):
  File "nikegen.py", line 15, in <module>
    from nikereqpatch import *
  File "/Users/HB77/Desktop/NikeAccountGenerator-master/nikereqpatch.py", line 2, in <module>
    import user_agents
ImportError: No module named user_agents

**Comment by hayess89** [comment]
You are missing the module user_agents.

You need to pip install user_agents

**Comment by sonya75** [comment]
Yeah. Anyway, the generator isn't working right now.
