### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by miles1998** [sonya75/NikeAccountGenerator#15]
403 Client Error: Forbidden for url: https://api.nike.com/idn/shim/profile/services/users

**Comment by theweavrs** [comment]
Can confirm. Seems Nike has blocked this URL.

**Comment by sonya75** [comment]
Yes, to be exact, Nike applied Akamai's bot detection for that url. And the bot detection bypass used in the script doesn't work anymore.

**Comment by SkeletonKing** [comment]
Hi, sonya75.
I want to bypass  nike akamai bot detection. Is it possible?
