### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by Gamunji** [sonya75/NikeAccountGenerator#22]
`Signing up with email ree.u.me+7ax@gmail.com
Error creating account
403 Client Error: Forbidden for url: https://api.nike.com/idn/shim/profile/services/users`

I can install numpy to use the slow gen, this is for the fast one

**Comment by sonya75** [comment]
None of them work. To use either, you now have to pass Akamai's bot detection and they can't anymore. I won't post the update for now.
