### ISSUE TITLE
Error When Running Generators

### ISSUE THREAD

**Issue by Dancull47** [sonya75/NikeAccountGenerator#25]
When using Fast Generator I get this error: 

Error creating account
403 Client Error: Forbidden for url: https://api.nike.com/idn/shim/profile/services/users

When using normal I get:

Error creating account
400 Client Error: Bad Request for url: https://unite.nike.com/access/users/v1?appVersion=389&experienceVersion=325&uxid=com.nike.commerce.nikedotcom.web&locale=en_US&backendEnvironment=identity&browser=Google%20Inc.&os=undefined&mobile=false&native=false&visit=2&visitor=06850bc1-2f9c-4557-809a-e91a505451be&language=en-US

**Comment by samuelmi** [comment]
same issue here..

**Comment by emilgora** [comment]
I have this issue too. I suspect that Nike has switched up their sign up method.

**Comment by sonya75** [comment]
Fixed.
