### ISSUE TITLE
400 Client Error Bad Request for URL

### ISSUE THREAD

**Issue by UnVeil24** [sonya75/NikeAccountGenerator#27]
Nike must've changed something so the request doesnt work

**Comment by maahyar** [comment]
would appreciate a response to the above issue

**Comment by SuddleD** [comment]
You all realize the script hasn't been updated or worked in over a month right? I wouldn't expect a fix anytime soon. Nike keeps changing end points and others are making money off account generating, so a free tool might be not available any time soon again.

**Comment by sonya75** [comment]
Fixed.
