### ISSUE TITLE
Help i'm dumb

### ISSUE THREAD

**Issue by UnVeil24** [sonya75/NikeAccountGenerator#28]
Traceback (most recent call last):
  File "nikegen.py", line 1, in <module>
    from ssl import SSLSocket,PROTOCOL_TLSv1_1
ImportError: cannot import name PROTOCOL_TLSv1_1

**Comment by sonya75** [comment]
What python version are you running it on? Its best to run it in python 2.7.15

**Comment by UnVeil24** [comment]
@sonya75 I am running on python 2.7.15

**Comment by sonya75** [comment]
I don't think that's possible. TLS v1.2 was introduced in Openssl v1.0.1 and Python 2.7.14 and 2.7.15 in the python official website are both compiled with Openssl 1.0.2k, so it should be there.

**Comment by UnVeil24** [comment]
Yes you are correct. I had 2.17.13. It's working perfectly now! Thanks for updating!
