### ISSUE TITLE
403 Client error forbidden url

### ISSUE THREAD

**Issue by UnVeil24** [sonya75/NikeAccountGenerator#31]
Nike fixed already?

**Comment by jonjosh** [comment]
I'm getting this error even on residential proxies:

403 Client Error: Forbidden for url: https://unite.nike.com/access/users/v1?appVersion=435&experienceVersion=361&uxid=com.nike.commerce.nikedotcom.web&locale=en_US&backendEnvironment=identity&browser=Google%20Inc.&os=undefined&mobile=false&native=false&visit=2&visitor=4c98d55e-0545-432a-8709-d4ea04959bb3&language=en-US

**Comment by bbridges11** [comment]
You need to find the new appversion and experienceversion

**Comment by UnVeil24** [comment]
@bbridges11 How do you do that? I'm pretty sure just means the proxy is banned as I've gotten to learn.

**Comment by ZachWhitford** [comment]
@UnVeil24 what is the current app version and experience version?

**Comment by UnVeil24** [comment]
@ZachWhitford idk

**Comment by sonya75** [comment]
I have pushed some updates, but the solution is basically to switch the ssl version in the config or use new proxies and keep thread limit low depending on proxy list size, so it doesn't spam.

**Comment by UnVeil24** [comment]
@sonya75 Cool thanks!
