### ISSUE TITLE
Https issue

### ISSUE THREAD

**Issue by UnVeil24** [sonya75/NikeAccountGenerator#32]
HTTPSConnectionPool(host='www.nike.com', port=443): Max retries exceeded with url: /_bm/_data (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))

**Comment by bbridges11** [comment]
I'm sure you are having a proxy error

**Comment by UnVeil24** [comment]
I was and I figured that out thanks though.
