### ISSUE TITLE
Error getting abck cookie

### ISSUE THREAD

**Issue by j-ip** [sonya75/NikeAccountGenerator#33]
HTTPSConnectionPool(host='www.nike.com', port=443): Max retries exceeded with url: /_bm/_data (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000D2D7F60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))

Got this error at first. I changed the https to http from inside Nikegen.py and the error goes away. But I still the error getting abck cookie. Any ideas? I've tried both my proxy lists and the same thing happens.

**Comment by sonya75** [comment]
You can't change to http. That getaddrinfo failed error means, it was unable to resolve the proxy host name, the issue is with your proxy.

**Comment by j-ip** [comment]
Thanks for the reply. I took proxies out the equation and I am still receiving the error getting abck cookie. What should I look into now?
