### ISSUE TITLE
get abck cookie error

### ISSUE THREAD

**Issue by Jackie0911** [sonya75/NikeAccountGenerator#36]
At first I can register,then I got get abck cookie error.After a while I register some accounts,and got this error again.whether with proxy or without proxy.Any idea on how to resolve this problem?

**Comment by sonya75** [comment]
You have to use a lot of proxies on which this method still works. For each IP, it won't work more than a few times per day.

**Comment by denaltheclone** [comment]
Getting this and I haven't been able to make any accounts at all. Trying to make a few to try it out and getting this error.
