### ISSUE TITLE
Error Creating Account And Error Getting Cookie on new update

### ISSUE THREAD

**Issue by UnVeil24** [sonya75/NikeAccountGenerator#37]
Trying to get abck cookie
Error getting cookie
Error creating account
Error getting cookie
Trying to get abck cookie

This is all it says.

**Comment by jjmomanyis** [comment]
I am having the same error! What might be the problem?

**Comment by sonya75** [comment]
You need to use a lot of residential proxies. It won't work with all IPs all the time. Will only work with a lot of proxies.

**Comment by UnVeil24** [comment]
That's not the problem. I have 200 resis loaded and it right away says that.
