### ISSUE TITLE
akamai bypass patched 

### ISSUE THREAD

**Issue by yzygang** [sonya75/NikeAccountGenerator#38]
akamai bypass patched

**Comment by jonjosh** [comment]
Why do you say this? Any proof?

**Comment by yzygang** [comment]
<img width="484" alt="screen shot 2018-06-11 at 12 16 46 am" src="https://user-images.githubusercontent.com/25470688/41217451-c5d08ecc-6d0c-11e8-9443-2167760776d5.png">

**Comment by sonya75** [comment]
That doesn't look like the latest version and no, it wasn't patched.
