### ISSUE TITLE
"Error getting a cookie", "Error creating account"

### ISSUE THREAD

**Issue by CJerome5** [sonya75/NikeAccountGenerator#40]
Anyone know how to fix this?
I saw in past issues that others were having problems because they didnt have enough proxies but I have about 250 residential proxies.

![image](https://user-images.githubusercontent.com/34609532/41267375-471ff5a0-6dc9-11e8-89f7-a70b929f4298.png)
![image](https://user-images.githubusercontent.com/34609532/41267441-7f1d3cb0-6dc9-11e8-8821-616256c16ab2.png)

**Comment by sonya75** [comment]
Have you tried switching the sslversion in nikeconfig.json from 3 to 4 ? Its mentioned in the readme.

**Comment by CJerome5** [comment]
yes, i have and I still get the same error.

**Comment by MattSmithASU** [comment]
Same thing for me, I have tried two different local ips and google cloud proxies

**Comment by CJerome5** [comment]
@MattSmithASU are you using a mac or pc?

**Comment by CJerome5** [comment]
@sonya75 would the type/version of Python installation be a problem?

**Comment by sonya75** [comment]
Try latest version of the script. I updated it just now.

**Comment by theweavrs** [comment]
@sonya75 still getting the same error.
