### ISSUE TITLE
always error "Error getting cookie"

### ISSUE THREAD

**Issue by wufengleo** [sonya75/NikeAccountGenerator#42]
i use dynamic IP,huge ip
but fail
may akamai patch it
i always got error
i try print cookies
any idea

B86FDCCA59382FDB9C7ED3D353449C447AE00AA60E7F00005A8F1F5B1403674C~-1~DtD2d2FP3v+QjzzbrDkJp0o7TU0c4+rKD98+qFD5T3k=~-1~-1
Error getting cookie
Error creating account
Error getting cookie
Trying to get abck cookie
A189538AD53B88565E88AB297212C2177AE00AA60E7F00005B8F1F5B8E0B2D73~-1~RdnxmLuEwFlIA+QrWerSXEbNLOp57keo7Ay+y203gK8=~-1~-1
Error getting cookie
Error creating account
Error getting cookie

**Comment by sonya75** [comment]
Try changing the sslversion from 3 to 4 in nikeconfig.json file.

**Comment by wufengleo** [comment]
i use 4 that

**Comment by Mejchalos** [comment]
getting the same error, but only sometimes, it lets me generate a few accounts and than all i get is error getting back cookie, i use sslversion 4

**Comment by Mejchalos** [comment]
i use rotating endpoints with thousands of ips in pool

**Comment by Mejchalos** [comment]
i have been testing it for few hours, only lets me generate 28-29 accounts before getting error getting cookie, after 1hour it lets me generate another 28-29 accounts, it does not make any sense i have much more proxies than 28-29

**Comment by wufengleo** [comment]
same issue
i close script,and open later
some times may success generate some account,but soon issue again
even i use new proxy not used

**Comment by Mejchalos** [comment]
Been testing it, time interval between being able to generate again is 30 minutes

**Comment by Mejchalos** [comment]
So let me make it clear.

Im able to generate without any problems for 4 minutes 28 accounts, after that all i get is error getting back cookies/error creating account.
After 30 minutes i can generate for another 4 minutes 28 accounts.
Looping excatly like this.

**Comment by wufengleo** [comment]
akamai hard by pass
i use Browser simulation also easy be return 403 error

**Comment by sonya75** [comment]
Try latest version of the script. I updated it just now.

**Comment by theweavrs** [comment]
@sonya75 still getting the same error.
