### ISSUE TITLE
Constant Error Getting Cookies

### ISSUE THREAD

**Issue by dantheman55** [sonya75/NikeAccountGenerator#43]
Do you want to continue?  [y/N]: y
Trying to get abck cookie
Error getting cookieTrying to get abck cookie

Error creating account
Error getting cookie
Error getting cookieTrying to get abck cookie

Error creating account
Error getting cookie

and over and over and over again.

I changed 	"sslversion": between 3 and 4 nothing changes.

**Comment by CJerome5** [comment]
I'm getting the same error

**Comment by LuckySim** [comment]
same here

**Comment by WCM3** [comment]
Are you guys able to generate any accounts before the cookie error?

**Comment by LuckySim** [comment]
No i cant create anything

Simon ADDI
étudiant epitech promo 2020
06 43 56 65 00
simon.addi@hotmail.com

________________________________

**Comment by LuckySim** [comment]
nop, can't create any

**Comment by dantheman55** [comment]
Nope^

**Comment by CJerome5** [comment]
i can't either. I know one guy who gets the error but it eventually swarms with code and makes him accounts

**Comment by Mikalangelo** [comment]
I'm also getting the error.

**Comment by walmat** [comment]
+1

**Comment by sonya75** [comment]
Try latest version of the script. I updated it just now.

**Comment by theweavrs** [comment]
@sonya75 still getting the same error.
