### ISSUE TITLE
Failed to get cookies

### ISSUE THREAD

**Issue by bypasses** [sonya75/NikeAccountGenerator#60]
![image](https://user-images.githubusercontent.com/33882429/56854216-d7b4bd00-692a-11e9-8031-ef621517299f.png)

**Comment by brad1405** [comment]
@sonya75 please help :P

**Comment by DillonMercz** [comment]
I get this same error. Did you solve it?

**Comment by mnbv1775** [comment]
I solve it after rewrite the code.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sonya75/NikeAccountGenerator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月30日(星期五) 上午6:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [sonya75/NikeAccountGenerator] Failed to get cookies (#60)





 
I get this same error. Did you solve it?

**Comment by Mobeen-Ghaffar** [comment]
> I solve it after rewrite the code.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sonya75/NikeAccountGenerator" ***@***.***&gt;; 发送时间:&nbsp;2021年4月30日(星期五) 上午6:16 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [sonya75/NikeAccountGenerator] Failed to get cookies (#60) I get this same error. Did you solve it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

How u resolved it?
Is there any issue in code?

**Comment by mnbv1775** [comment]
> > I solve it after rewrite the code.
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "sonya75/NikeAccountGenerator" _**@**_._**>; 发送时间: 2021年4月30日(星期五) 上午6:16 _**@**_.**_>; _**@**_.***>; 主题: Re: [sonya75/NikeAccountGenerator] Failed to get cookies (#60) I get this same error. Did you solve it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> How u resolved it?
> Is there any issue in code?



> > I solve it after rewrite the code.
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "sonya75/NikeAccountGenerator" _**@**_._**>; 发送时间: 2021年4月30日(星期五) 上午6:16 _**@**_.**_>; _**@**_.***>; 主题: Re: [sonya75/NikeAccountGenerator] Failed to get cookies (#60) I get this same error. Did you solve it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> How u resolved it?
> Is there any issue in code?

By author of this code thinking, tran all of sensor.js to python.

![image](https://user-images.githubusercontent.com/17544980/122723268-599f9700-d2a5-11eb-9d88-1069f6db9c37.png)
